CREATE TABLE [dbo].[tabC] (
    [PKID_C]           NCHAR (36)     CONSTRAINT [DF_tabC_PKID_C] DEFAULT ('') NOT NULL,
    [txtCOLOR]         NCHAR (36)     CONSTRAINT [DF_tabC_txtCOLOR] DEFAULT ('') NOT NULL,
    [txtDate]          NCHAR (36)     CONSTRAINT [DF_tabC_txtDate] DEFAULT ('') NOT NULL,
    [txtDateTime]      NCHAR (36)     CONSTRAINT [DF_tabC_txtDateTime] DEFAULT ('') NOT NULL,
    [txtDateTimeLocal] NCHAR (36)     CONSTRAINT [DF_tabC_txtDateTimeLocal] DEFAULT ('') NOT NULL,
    [txtEmail]         NCHAR (36)     CONSTRAINT [DF_tabC_txtEmail] DEFAULT ('') NOT NULL,
    [txtMonth]         NCHAR (36)     CONSTRAINT [DF_tabC_txtMonth] DEFAULT ('') NOT NULL,
    [txtMultiLine]     NCHAR (36)     CONSTRAINT [DF_tabC_txtMultiLine] DEFAULT ('') NOT NULL,
    [txtNumber]        NCHAR (36)     CONSTRAINT [DF_tabC_txtNumber] DEFAULT ('') NOT NULL,
    [txtPassword]      NCHAR (36)     CONSTRAINT [DF_tabC_txtPassword] DEFAULT ('') NOT NULL,
    [txtPhone]         NCHAR (36)     CONSTRAINT [DF_tabC_txtPhone] DEFAULT ('') NOT NULL,
    [txtRange]         NCHAR (36)     CONSTRAINT [DF_tabC_txtRange] DEFAULT ('') NOT NULL,
    [txtSearch]        NCHAR (36)     CONSTRAINT [DF_tabC_txtSearch] DEFAULT ('') NOT NULL,
    [txtSingleLine]    NCHAR (36)     CONSTRAINT [DF_tabC_txtSingleLine] DEFAULT ('') NOT NULL,
    [txtTime]          NCHAR (36)     CONSTRAINT [DF_tabC_txtTime] DEFAULT ('') NOT NULL,
    [txtUrl]           NCHAR (36)     CONSTRAINT [DF_tabC_txtUrl] DEFAULT ('') NOT NULL,
    [txtWeek]          NCHAR (36)     CONSTRAINT [DF_tabC_txtWeek] DEFAULT ('') NOT NULL,
    [mask]             TINYINT        CONSTRAINT [DF_tabC_mask] DEFAULT ((7)) NOT NULL,
    [CreateBy]         NVARCHAR (50)  CONSTRAINT [DF_tabC_CreateBy] DEFAULT ('') NOT NULL,
    [ReviseBy]         NVARCHAR (50)  CONSTRAINT [DF_tabC_ReviseBy] DEFAULT ('') NOT NULL,
    [DeleteBy]         NVARCHAR (50)  CONSTRAINT [DF_tabC_DeleteBy] DEFAULT ('') NOT NULL,
    [CreateTime]       DATETIME       CONSTRAINT [DF_tabC_CreateTime] DEFAULT (getdate()) NOT NULL,
    [ReviseTime]       DATETIME       CONSTRAINT [DF_tabC_ReviseTime] DEFAULT (getdate()) NOT NULL,
    [DeleteTime]       DATETIME       NULL,
    [CreateGrp]        NVARCHAR (255) CONSTRAINT [DF_tabC_CreateGrp] DEFAULT ('') NOT NULL,
    [ReviseGrp]        NVARCHAR (255) CONSTRAINT [DF_tabC_ReviseGrp] DEFAULT ('') NOT NULL,
    [DeleteGrp]        NVARCHAR (255) CONSTRAINT [DF_tabC_DeleteGrp] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_tabC] PRIMARY KEY CLUSTERED ([PKID_C] ASC)
);

