CREATE TABLE [dbo].[tabD] (
    [PKID_D]           NCHAR (36)     CONSTRAINT [DF_tabD_PKID_D] DEFAULT ('') NOT NULL,
    [txtCOLOR]         NCHAR (36)     CONSTRAINT [DF_tabD_txtCOLOR] DEFAULT ('') NOT NULL,
    [txtDate]          NCHAR (36)     CONSTRAINT [DF_tabD_txtDate] DEFAULT ('') NOT NULL,
    [txtDateTime]      NCHAR (36)     CONSTRAINT [DF_tabD_txtDateTime] DEFAULT ('') NOT NULL,
    [txtDateTimeLocal] NCHAR (36)     CONSTRAINT [DF_tabD_txtDateTimeLocal] DEFAULT ('') NOT NULL,
    [txtEmail]         NCHAR (36)     CONSTRAINT [DF_tabD_txtEmail] DEFAULT ('') NOT NULL,
    [txtMonth]         NCHAR (36)     CONSTRAINT [DF_tabD_txtMonth] DEFAULT ('') NOT NULL,
    [txtMultiLine]     NCHAR (36)     CONSTRAINT [DF_tabD_txtMultiLine] DEFAULT ('') NOT NULL,
    [txtNumber]        NCHAR (36)     CONSTRAINT [DF_tabD_txtNumber] DEFAULT ('') NOT NULL,
    [txtPassword]      NCHAR (36)     CONSTRAINT [DF_tabD_txtPassword] DEFAULT ('') NOT NULL,
    [txtPhone]         NCHAR (36)     CONSTRAINT [DF_tabD_txtPhone] DEFAULT ('') NOT NULL,
    [txtRange]         NCHAR (36)     CONSTRAINT [DF_tabD_txtRange] DEFAULT ('') NOT NULL,
    [txtSearch]        NCHAR (36)     CONSTRAINT [DF_tabD_txtSearch] DEFAULT ('') NOT NULL,
    [txtSingleLine]    NCHAR (36)     CONSTRAINT [DF_tabD_txtSingleLine] DEFAULT ('') NOT NULL,
    [txtTime]          NCHAR (36)     CONSTRAINT [DF_tabD_txtTime] DEFAULT ('') NOT NULL,
    [txtUrl]           NCHAR (36)     CONSTRAINT [DF_tabD_txtUrl] DEFAULT ('') NOT NULL,
    [txtWeek]          NCHAR (36)     CONSTRAINT [DF_tabD_txtWeek] DEFAULT ('') NOT NULL,
    [mask]             TINYINT        CONSTRAINT [DF_tabD_mask] DEFAULT ((7)) NOT NULL,
    [CreateBy]         NVARCHAR (50)  CONSTRAINT [DF_tabD_CreateBy] DEFAULT ('') NOT NULL,
    [ReviseBy]         NVARCHAR (50)  CONSTRAINT [DF_tabD_ReviseBy] DEFAULT ('') NOT NULL,
    [DeleteBy]         NVARCHAR (50)  CONSTRAINT [DF_tabD_DeleteBy] DEFAULT ('') NOT NULL,
    [CreateTime]       DATETIME       CONSTRAINT [DF_tabD_CreateTime] DEFAULT (getdate()) NOT NULL,
    [ReviseTime]       DATETIME       CONSTRAINT [DF_tabD_ReviseTime] DEFAULT (getdate()) NOT NULL,
    [DeleteTime]       DATETIME       NULL,
    [CreateGrp]        NVARCHAR (255) CONSTRAINT [DF_tabD_CreateGrp] DEFAULT ('') NOT NULL,
    [ReviseGrp]        NVARCHAR (255) CONSTRAINT [DF_tabD_ReviseGrp] DEFAULT ('') NOT NULL,
    [DeleteGrp]        NVARCHAR (255) CONSTRAINT [DF_tabD_DeleteGrp] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_tabD] PRIMARY KEY CLUSTERED ([PKID_D] ASC)
);

